export const PackageData = [
  {
    id: 1,
    img: "/caba.jpeg",
    title: "Premium Hajj",
    location: "Dec 10 - Dec 15",
    guide: "Document Guide",
    hotel: "5 Stars Hotel",
    meals: "Local Meals",
    visa: "Visa Included",
    // description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 6700,
    type: "Cultural Relax",
  },
  {
    id: 2,
    img: "/modina.webp",
    title: "Ramadan Umrah",
    location: "Dec 10 - Dec 15",
    guide: "Document Guide",
    hotel: "5 Stars Hotel",
    meals: "Local Meals",
    visa: "Visa Included",
    description:
      "The Taj Mahal is an ivory-white marble mausoleum on the south bank of the river Yamuna in the Indian city of Agra.",
    price: 6700,
    type: "Cultural Relax",
  },
  {
    id: 3,
    img: "/clock-tower.jpeg",
    title: "Family Umrah",
    location: "Dec 10 - Dec 15",
    guide: "Document Guide",
    hotel: "5 Stars Hotel",
    meals: "Local Meals",
    visa: "Visa Included",
    description:
      "The Taj Mahal is an ivory-white marble mausoleum on the south bank of the river Yamuna in the Indian city of Agra.",
    price: 6200,
    type: "Cultural Relax",
  },
  {
    id: 4,
    img: "/nuts.webp",
    title: "Medina City Tour",
    location: "Dec 10 - Dec 15",
    guide: "Document Guide",
    hotel: "5 Stars Hotel",
    meals: "Local Meals",
    visa: "Visa Included",
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 6700,
    type: "Cultural Relax",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/7042325/pexels-photo-7042325.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    title: "Nabawi Tour",
    location: "Dec 10 - Dec 15",
    guide: "Document Guide",
    hotel: "5 Stars Hotel",
    meals: "Local Meals",
    visa: "Visa Included",
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 6700,
    type: "Cultural Relax",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/2042108/pexels-photo-2042108.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    title: "Umrah Group",
    location: "Dec 10 - Dec 15",
    guide: "Document Guide",
    hotel: "5 Stars Hotel",
    meals: "Local Meals",
    visa: "Visa Included",
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 6700,
    type: "Cultural Relax",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/27697387/pexels-photo-27697387/free-photo-of-a-white-building-with-a-red-flag-in-the-middle.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    title: "Saudi Tour",
    location: "Dec 10 - Dec 15",
    guide: "Document Guide",
    hotel: "5 Stars Hotel",
    meals: "Local Meals",
    visa: "Visa Included",
    // description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 6700,
    type: "Cultural Relax",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/17928133/pexels-photo-17928133/free-photo-of-blue-dome-in-medina.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    title: "Rawdha Package",
    location: "Dec 10 - Dec 15",
    guide: "Document Guide",
    hotel: "5 Stars Hotel",
    meals: "Local Meals",
    visa: "Visa Included",
    description:
      "The Taj Mahal is an ivory-white marble mausoleum on the south bank of the river Yamuna in the Indian city of Agra.",
    price: 6700,
    type: "Cultural Relax",
  },
  {
    id: 9,
    img: "https://images.pexels.com/photos/2787826/pexels-photo-2787826.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    title: "Reguler Hajj",
    location: "Dec 10 - Dec 15",
    guide: "Document Guide",
    hotel: "5 Stars Hotel",
    meals: "Local Meals",
    visa: "Visa Included",
    description:
      "The Taj Mahal is an ivory-white marble mausoleum on the south bank of the river Yamuna in the Indian city of Agra.",
    price: 6200,
    type: "Cultural Relax",
  },
  {
    id: 10,
    img: "https://images.pexels.com/photos/28291079/pexels-photo-28291079/free-photo-of-men-riding-a-camel.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    title: "Umrah + Thaif",
    location: "Dec 10 - Dec 15",
    guide: "Document Guide",
    hotel: "5 Stars Hotel",
    meals: "Local Meals",
    visa: "Visa Included",
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 6700,
    type: "Cultural Relax",
  },
  {
    id: 11,
    img: "https://images.pexels.com/photos/15787268/pexels-photo-15787268/free-photo-of-prophets-mosque-in-medina.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    title: "Umrah Plus Dubai",
    location: "Dec 10 - Dec 15",
    guide: "Document Guide",
    hotel: "5 Stars Hotel",
    meals: "Local Meals",
    visa: "Visa Included",
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 6700,
    type: "Cultural Relax",
  },
  {
    id: 12,
    img: "https://images.pexels.com/photos/19021371/pexels-photo-19021371/free-photo-of-man-praying-in-muslim-temple.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    title: "Premium Hajj",
    location: "Dec 10 - Dec 15",
    guide: "Document Guide",
    hotel: "5 Stars Hotel",
    meals: "Local Meals",
    visa: "Visa Included",
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    price: 6700,
    type: "Cultural Relax",
  },
];
